# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171027_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemversion',
            old_name='logo_orig',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='name',
        ),
    ]
