# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171027_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversionmetadata',
            name='system',
        ),
        migrations.AddField(
            model_name='systemversion',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SystemVersionMetadata'),
        ),
    ]
