# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171030_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='current_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
