# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171030_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='label',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
