# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 21:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171031_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='logos/'),
        ),
    ]
