# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171108_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfeatures',
            name='description',
            field=models.TextField(default='', help_text='This field support Markdown Syntax'),
            preserve_default=False,
        ),
    ]
