# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemfeatures_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
