# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171205_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='version_message',
        ),
    ]
