# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_systemversion_version_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='systemversionmetadata',
            name='derived_from',
        ),
        migrations.AddField(
            model_name='systemversionmetadata',
            name='derived_from',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='systemfeatures',
            name='citation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CitationUrls'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='description_citations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_descriptions', to='core.CitationUrls'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='end_year_citations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_end_years', to='core.CitationUrls'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='history_citations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_histories', to='core.CitationUrls'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='start_year_citations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_start_years', to='core.CitationUrls'),
        ),
    ]
