# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171207_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemfeatures',
            name='citation',
        ),
        migrations.AddField(
            model_name='systemfeatures',
            name='citation',
            field=models.ManyToManyField(null=True, to='core.CitationUrls'),
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='description_citations',
        ),
        migrations.AddField(
            model_name='systemversion',
            name='description_citations',
            field=models.ManyToManyField(null=True, related_name='version_descriptions', to='core.CitationUrls'),
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='end_year_citations',
        ),
        migrations.AddField(
            model_name='systemversion',
            name='end_year_citations',
            field=models.ManyToManyField(null=True, related_name='version_end_years', to='core.CitationUrls'),
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='history_citations',
        ),
        migrations.AddField(
            model_name='systemversion',
            name='history_citations',
            field=models.ManyToManyField(null=True, related_name='version_histories', to='core.CitationUrls'),
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='start_year_citations',
        ),
        migrations.AddField(
            model_name='systemversion',
            name='start_year_citations',
            field=models.ManyToManyField(null=True, related_name='version_start_years', to='core.CitationUrls'),
        ),
    ]
