# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171207_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationurls',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='license',
            name='website',
            field=models.URLField(default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='website',
            field=models.URLField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='website',
            field=models.URLField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedsystem',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='tech_docs',
            field=models.URLField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='website',
            field=models.URLField(blank=True, default='', max_length=512, null=True),
        ),
    ]
