# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180202_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
