# Generated by Django 2.0.3 on 2018-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
