# Generated by Django 2.0.3 on 2018-04-12 23:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemversion_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of where the DBMS company or project started', max_length=746, multiple=True, verbose_name='Countries of Origin'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL of where to download source code (if available)', max_length=500, verbose_name='Source Code URL'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='tech_docs',
            field=models.URLField(blank=True, help_text='URL of the where to find technical documentation about the DBMS', max_length=500),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the DBMS company or project', max_length=500),
        ),
    ]
