# Generated by Django 2.0.3 on 2018-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180412_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='former_names',
            field=models.CharField(blank=True, help_text='Previous names of the system', max_length=100),
        ),
    ]
