# Generated by Django 2.0.3 on 2018-04-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemversion_former_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='acquired_by',
            field=models.CharField(blank=True, help_text='Name of the company that first acquired the DBMS', max_length=32),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='acquired_by_citations',
            field=models.ManyToManyField(blank=True, related_name='version_acquired_bys', to='core.CitationUrl'),
        ),
    ]
