# Generated by Django 2.0.3 on 2018-05-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180427_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversionmetadata',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, help_text='Other systems that this system is compatible with (e.g., wire protocol, file formats).', related_name='compatible_with_systems', to='core.System', verbose_name='Systems Compatible With'),
        ),
        migrations.AddField(
            model_name='systemversionmetadata',
            name='inspired_by',
            field=models.ManyToManyField(blank=True, help_text='Systems used for inspiration in its design but did not rely on source code', related_name='inspired_by_systems', to='core.System', verbose_name='Systems Inspired By'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='developer',
            field=models.CharField(blank=True, help_text='The original organization that developed the DBMS.', max_length=500),
        ),
        migrations.AlterField(
            model_name='systemversionmetadata',
            name='derived_from',
            field=models.ManyToManyField(blank=True, help_text='Systems that this system uses or its source code is based on', related_name='derived_from_systems', to='core.System', verbose_name='Systems Derived From'),
        ),
    ]
