# Generated by Django 2.0.3 on 2018-05-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180528_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='URL of Wikipedia article about this system (if available)', max_length=500, verbose_name='Wikipedia URL'),
        ),
    ]
