# Generated by Django 2.0.3 on 2018-06-07 05:35

from django.db import migrations


def fix(apps, schema_editor):
    from django_countries.fields import Country
    SystemVersion = apps.get_model('core', 'SystemVersion')
    
    for sv in SystemVersion.objects.all():
        if not isinstance(sv.countries, list): continue
        if len( sv.countries ) == 0: continue
        if str(sv.countries[0]) != '[': continue

        sv.countries = eval( ''.join(list(map(str,sv.countries))).replace(' ',',') )
        sv.save()
        pass
    return

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemversion_wikipedia_url'),
    ]

    operations = [
        migrations.RunPython(fix),
    ]
