# Generated by Django 2.0.6 on 2018-08-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, help_text='This field supports Markdown Syntax'),
        ),
        migrations.AddField(
            model_name='featureoption',
            name='description',
            field=models.TextField(blank=True, help_text='This field supports Markdown Syntax'),
        ),
    ]
