# Generated by Django 2.0.9 on 2018-12-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemredirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureoption',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.Feature'),
        ),
        migrations.AlterField(
            model_name='systemfeature',
            name='citations',
            field=models.ManyToManyField(related_name='system_features', to='core.CitationUrl'),
        ),
        migrations.AlterField(
            model_name='systemfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_features', to='core.Feature'),
        ),
        migrations.AlterField(
            model_name='systemfeature',
            name='options',
            field=models.ManyToManyField(related_name='system_features', to='core.FeatureOption'),
        ),
    ]
