# Generated by Django 2.0.9 on 2018-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181204_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
