# Generated by Django 2.0.6 on 2018-08-20 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180815_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, help_text='This field supports Markdown Syntax')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
