# Generated by Django 2.0.9 on 2018-12-04 11:09

from django.db import migrations


def populate(apps, schema_editor):
    from django.utils.text import slugify

    Feature = apps.get_model('core', 'Feature')

    for f in Feature.objects.all():
        f.slug = slugify( f.label )
        f.save()
        pass

    return

def depopulate(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feature_slug'),
    ]

    operations = [
        migrations.RunPython(populate, depopulate),
    ]
