# Generated by Django 2.0.9 on 2018-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feature_slug_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
