# Generated by Django 2.0.9 on 2018-12-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feature_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureoption',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
