# Generated by Django 2.0.13 on 2019-07-16 23:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190710_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='core.System')),
            ],
        ),
    ]
