# Generated by Django 2.0.13 on 2019-07-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_systemvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversionmetadata',
            name='embedded',
            field=models.ManyToManyField(blank=True, help_text='Systems that this system uses on the inside (e.g., storage manager)', related_name='embedded_systems', to='core.System', verbose_name='Systems Embedded'),
        ),
        migrations.AlterField(
            model_name='systemversionmetadata',
            name='derived_from',
            field=models.ManyToManyField(blank=True, help_text="Systems that this system's source code is based on", related_name='derived_from_systems', to='core.System', verbose_name='Systems Derived From'),
        ),
    ]
