# Generated by Django 2.0.13 on 2019-07-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_systemrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemacl',
            options={'verbose_name': 'Permission'},
        ),
        migrations.AlterModelOptions(
            name='systemrecommendation',
            options={'verbose_name': 'Recommendation'},
        ),
        migrations.AlterModelOptions(
            name='systemvisit',
            options={'verbose_name': 'Visit'},
        ),
        migrations.AlterUniqueTogether(
            name='systemrecommendation',
            unique_together={('system', 'recommendation')},
        ),
    ]
