# Generated by Django 2.0.13 on 2019-07-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190719_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrecommendation',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
