# Generated by Django 3.1.14 on 2022-01-02 19:37

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_systemrecommendation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of where the DBMS company or project started', max_length=749, multiple=True, verbose_name='Countries of Origin'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.system'),
        ),
        migrations.AlterField(
            model_name='systemvisit',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.system'),
        ),
    ]
