# Generated by Django 3.1.14 on 2022-06-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_systemversion_twitter_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True, help_text='This field supports Markdown Syntax'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.Tag', verbose_name='Tag'),
        ),
    ]
