# Generated by Django 3.1.14 on 2022-06-26 19:11

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220626_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemversion',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, upload_to='logos/'),
        ),
    ]
