# Generated by Django 4.1.3 on 2023-07-03 18:03
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_systemversion_countries'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension()
    ]
