# Generated by Django 4.1.3 on 2023-07-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_systemsearchtext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemfeature',
            old_name='system',
            new_name='version',
        ),
        migrations.AlterUniqueTogether(
            name='systemfeature',
            unique_together={('version', 'feature')},
        ),
    ]
