# Generated by Django 4.1.10 on 2023-07-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_systemsearchtext_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL of LinkedIn profile for main developer backing the system (if available)', max_length=500, verbose_name='LinkedIn URL'),
        ),
    ]
