# Generated by Django 4.1.10 on 2023-11-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_systemsearchtext_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationurl',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
