# Generated by Django 4.1.10 on 2025-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_systemversion_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(default='FIXME', max_length=64),
            preserve_default=False,
        ),
    ]
