# Generated by Django 4.1.10 on 2025-11-27 16:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='logo_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='The color of the logo', image_field=None, max_length=25, samples=None),
        ),
    ]
