# Generated by Django 4.1.10 on 2025-12-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_systemversion_logo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='derived_from',
            field=models.ManyToManyField(blank=True, help_text="Systems that this system's source code is based on", related_name='derived_from_systemsX', to='core.system', verbose_name='Systems Derived From'),
        ),
    ]
