# Generated by Django 4.1.10 on 2025-12-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_systemversion_derived_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversionmetadata',
            name='derived_from',
        ),
    ]
