# Generated by Django 4.1.10 on 2025-12-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_systemversionmetadata_derived_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, help_text='Other systems that this system is compatible with (e.g., wire protocol, file formats).', related_name='compatible_with_systemsX', to='core.system', verbose_name='Systems Compatible With'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='embedded',
            field=models.ManyToManyField(blank=True, help_text='Systems that this system uses on the inside (e.g., storage manager)', related_name='embedded_systemsX', to='core.system', verbose_name='Systems Embedded'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='inspired_by',
            field=models.ManyToManyField(blank=True, help_text='Systems used for inspiration in its design but did not rely on source code', related_name='inspired_by_systemsX', to='core.system', verbose_name='Systems Inspired By'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='licenses',
            field=models.ManyToManyField(blank=True, related_name='systems_licensesX', to='core.license'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='oses',
            field=models.ManyToManyField(blank=True, related_name='systems_osesX', to='core.operatingsystem', verbose_name='Operating Systems'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='systems_publicationsX', to='core.publication'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='supported_languages',
            field=models.ManyToManyField(blank=True, related_name='systems_supportedX', to='core.programminglanguage', verbose_name='Supported Languages'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='written_in',
            field=models.ManyToManyField(blank=True, related_name='systems_writtenX', to='core.programminglanguage'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='derived_from',
            field=models.ManyToManyField(blank=True, help_text="Systems that this system's source code is based on", related_name='derived_from_systems', to='core.system', verbose_name='Systems Derived From'),
        ),
    ]
