# Generated by Django 4.1.10 on 2025-12-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_systemversion_compatible_with_systemversion_embedded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='publications',
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, help_text='Other systems that this system is compatible with (e.g., wire protocol, file formats).', related_name='compatible_with_systems', to='core.system', verbose_name='Systems Compatible With'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='embedded',
            field=models.ManyToManyField(blank=True, help_text='Systems that this system uses on the inside (e.g., storage manager)', related_name='embedded_systems', to='core.system', verbose_name='Systems Embedded'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='inspired_by',
            field=models.ManyToManyField(blank=True, help_text='Systems used for inspiration in its design but did not rely on source code', related_name='inspired_by_systems', to='core.system', verbose_name='Systems Inspired By'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='licenses',
            field=models.ManyToManyField(blank=True, related_name='systems_licenses', to='core.license'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='oses',
            field=models.ManyToManyField(blank=True, related_name='systems_oses', to='core.operatingsystem', verbose_name='Operating Systems'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='supported_languages',
            field=models.ManyToManyField(blank=True, related_name='systems_supported', to='core.programminglanguage', verbose_name='Supported Languages'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='written_in',
            field=models.ManyToManyField(blank=True, related_name='systems_written', to='core.programminglanguage'),
        ),
        migrations.DeleteModel(
            name='SystemVersionMetadata',
        ),
    ]
