# Generated by Django 4.1.10 on 2025-12-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_systemversion_meta_and_more'),
    ]

    operations = [
        # Migration 0031 renamed SystemFeature.system → version but PostgreSQL kept
        # the old auto-generated index name. Rename it here so the AddField below
        # can create a fresh index with the same auto-generated name for the new
        # system FK without hitting a name collision.
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes
                               WHERE indexname = 'core_systemfeature_system_id_717491a7') THEN
                        ALTER INDEX core_systemfeature_system_id_717491a7
                              RENAME TO core_systemfeature_version_id_717491a7;
                    END IF;
                END
                $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes
                               WHERE indexname = 'core_systemfeature_version_id_717491a7') THEN
                        ALTER INDEX core_systemfeature_version_id_717491a7
                              RENAME TO core_systemfeature_system_id_717491a7;
                    END IF;
                END
                $$;
            """,
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.system'),
        ),
    ]
