# Generated by Django 4.1.10 on 2025-12-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_systemversion_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfeature',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.system'),
        ),
    ]
