# Generated by Django 4.1.10 on 2025-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_systemfeature_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='logo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='logo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
