# Generated by Django 6.0 on 2025-12-11 16:55

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_systemversion_logo_height_systemversion_logo_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='systemversion',
            name='linkedin_handle',
            field=models.CharField(blank=True, help_text='LinkedIn profile for main developer backing the system (if available)', max_length=100, verbose_name='LinkedIn Handle'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of where the DBMS company or project started', max_length=746, multiple=True, verbose_name='Countries of Origin'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
