# Generated by Django 6.0 on 2025-12-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_systemversion_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfeature',
            name='system',
            field=models.ForeignKey(blank=True, default=None, help_text='Does this system inherit these features from another system', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.system'),
        ),
    ]
