# Generated by Django 6.0 on 2025-12-15 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_systemfeature_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationurl',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='citationurl',
            name='dead',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citationurl',
            name='last_checked',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citationurl',
            name='last_contenttype',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citationurl',
            name='last_status',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citationurl',
            name='last_title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
