# Generated by Django 6.0 on 2025-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_citationurl_created_citationurl_dead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationurl',
            name='last_cachecontrol',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='citationurl',
            name='last_etag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citationurl',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
