# Generated by Django 6.0 on 2025-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_citationurl_last_cachecontrol_citationurl_last_etag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationurl',
            name='last_contentsize',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
