# Generated by Django 6.0 on 2025-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_citationurl_last_contentsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationurl',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Valid'), (2, 'Dead'), (3, 'Spam')], default=0),
        ),
    ]
