# Generated by Django 6.0 on 2025-12-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_citationurl_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citationurl',
            old_name='last_status',
            new_name='last_statuscode',
        ),
        migrations.RemoveField(
            model_name='citationurl',
            name='dead',
        ),
    ]
