# Generated by Django 6.0.4 on 2026-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rename_last_status_citationurl_last_statuscode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citationurl',
            options={'verbose_name': 'Citation URL'},
        ),
        migrations.AlterField(
            model_name='citationurl',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Valid'), (2, 'Dead'), (3, 'Spam'), (4, 'Ignore')], default=0),
        ),
    ]
