# Generated by Django 6.0.4 on 2026-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_citationurl_options_alter_citationurl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='hosted_services',
            field=models.ManyToManyField(blank=True, help_text='Other DBMS systems that this system offers as a managed hosted DBaaS service (e.g., Amazon RDS hosting PostgreSQL). Do not include this system itself.', related_name='hosted_by_systems', to='core.system', verbose_name='Hosted DBaaS Services'),
        ),
    ]
