# Generated by Django 6.0.4 on 2026-05-22 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_systemversion_hosted_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='This field supports Markdown Syntax')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('linkedin_url', models.ForeignKey(blank=True, help_text="URL of the organization's LinkedIn page", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_linkedin_urls', to='core.citationurl')),
                ('url', models.ForeignKey(blank=True, help_text="URL of the organization's main website", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_urls', to='core.citationurl')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='systemversion',
            name='developer_orgs',
            field=models.ManyToManyField(blank=True, help_text='Organizations that developed this DBMS (structured alternative to the developer text field)', related_name='developed_systems', to='core.organization', verbose_name='Developer Organizations'),
        ),
    ]
