# Generated by Django 6.0.4 on 2026-05-23 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_organization_developer_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year the acquisition was completed', null=True)),
                ('citation', models.ForeignKey(blank=True, help_text='Source documenting this acquisition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions', to='core.citationurl')),
                ('organization', models.ForeignKey(help_text='The organization that acquired this system', on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='core.organization')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='core.systemversion')),
            ],
            options={
                'ordering': ('year', 'organization__name'),
                'unique_together': {('version', 'organization')},
            },
        ),
    ]
