# Generated by Django 6.0.4 on 2026-05-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_acquisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='acquired_by',
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='acquired_by_citations',
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='developer',
        ),
    ]
