# Generated by Django 6.0.4 on 2026-05-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_systemversion_acquired_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='docs_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_docs_urls', to='core.citationurl', verbose_name='Tech Docs URL'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='sourcerepo_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_sourcerepo_urls', to='core.citationurl', verbose_name='Source Code URL'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='system_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_system_urls', to='core.citationurl', verbose_name='Website URL'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='wikipedia_new_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_wikipedia_urls', to='core.citationurl', verbose_name='Wikipedia URL'),
        ),
    ]
