# Generated by Django 6.0.4 on 2026-05-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_systemversion_citationurl_url_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='tech_docs',
        ),
        migrations.RemoveField(
            model_name='systemversion',
            name='url',
        ),
        # Remove the legacy URLField first so the name is free for the rename below.
        migrations.RemoveField(
            model_name='systemversion',
            name='wikipedia_url',
        ),
        # Rename the FK (was wikipedia_new_url) to the now-free wikipedia_url name.
        migrations.RenameField(
            model_name='systemversion',
            old_name='wikipedia_new_url',
            new_name='wikipedia_url',
        ),
    ]