# Generated by Django 6.0.4 on 2026-05-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_legacy_url_fields_rename_wikipedia'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_navbar', models.BooleanField(default=False, help_text='Show this page as a link in the top navigation bar.')),
                ('nav_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which this page appears in the navbar (lower = first).')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='flatpages.flatpage')),
            ],
            options={
                'ordering': ['nav_order', 'page__title'],
            },
        ),
    ]
