# Generated by Django 6.0.4 on 2026-05-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_flatpagemeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='This field supports Markdown Syntax')),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True, help_text='This field supports Markdown Syntax')),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.attribute')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('attribute', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='systemversion',
            name='attr_licenses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'license'}, related_name='system_licenses', to='core.attributeoption', verbose_name='Licenses'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='attr_oses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'os'}, related_name='system_oses', to='core.attributeoption', verbose_name='Operating Systems'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='attr_project_types',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'project-type'}, related_name='system_project_types', to='core.attributeoption', verbose_name='Project Types'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='attr_supported_languages',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'programming-language'}, related_name='system_supported_languages', to='core.attributeoption', verbose_name='Supported Languages'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='attr_tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'tag'}, related_name='system_tags', to='core.attributeoption', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='attr_written_in',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'programming-language'}, related_name='system_written_in', to='core.attributeoption', verbose_name='Written In'),
        ),
    ]
