# Generated by Django 6.0.4 on 2026-05-28 18:48

import colorfield.fields
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_savedsearch_and_auto_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='The color of the logo', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
