# Generated by Django 6.0.4 on 2026-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_repositorysnapshot_branch_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='spotlight_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
