# Generated by Django 6.0.4 on 2026-05-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_system_spotlight_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='spotlight_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
