# Generated by Django 6.0.4 on 2026-06-01 01:15

from django.db import migrations, models


def backfill_approved(apps, schema_editor):
    # All pre-existing versions were once published, so mark them all approved.
    # Only new pending edits (created after this migration) should have approved=False.
    SystemVersion = apps.get_model('core', 'SystemVersion')
    SystemVersion.objects.all().update(approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_system_spotlight_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_approved, migrations.RunPython.noop),
    ]
