# Generated by Django 6.0.4 on 2026-06-02 20:23

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_systemversion_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Countries where this organization is headquartered', max_length=746, multiple=True, verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'org-type'}, related_name='org_types', to='core.attributeoption', verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stock_exchange',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'stock-exchange'}, related_name='org_stock_exchanges', to='core.attributeoption', verbose_name='Stock Exchange'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stock_symbol',
            field=models.CharField(blank=True, help_text='Ticker symbol (e.g. ORCL, MSFT)', max_length=20),
        ),
    ]
