# Generated by Django 6.0.4 on 2026-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_organization_attribute_seeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='stock_exchange',
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Company'), (2, 'University'), (3, 'Individual'), (4, 'Research Lab')], null=True, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stock_exchange',
            field=models.IntegerField(blank=True, choices=[(1, 'NYSE'), (2, 'NASDAQ'), (3, 'LSE'), (4, 'TSE'), (5, 'HKEX'), (6, 'ASX'), (7, 'TSX'), (8, 'Euronext'), (9, 'Other')], null=True, verbose_name='Stock Exchange'),
        ),
    ]
