# Generated by Django 6.0.4 on 2026-06-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_systemsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='secret_key',
        ),
    ]
