# Generated by Django 6.0.4 on 2026-06-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_drop_system_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='core.citationurl'),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='attribute_options', to='core.citationurl'),
        ),
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Storage & Data'), (2, 'Query Processing'), (3, 'Transactions & Concurrency'), (4, 'System & Reliability')], null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='features', to='core.citationurl'),
        ),
        migrations.AddField(
            model_name='featureoption',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='feature_options', to='core.citationurl'),
        ),
        migrations.AddField(
            model_name='featureoption',
            name='description',
            field=models.TextField(blank=True, default='', help_text='This field supports Markdown Syntax'),
        ),
    ]
