# Generated by Django 6.0.4 on 2026-06-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_populate_docpage_system_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationUrlContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField(blank=True, db_comment='Original HTML or PDF-extracted text from the crawled URL', default='')),
                ('text', models.TextField(blank=True, db_comment='Stripped, cleaned plain text for LLM context', default='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('citation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.citationurl')),
            ],
            options={
                'verbose_name': 'Citation URL Content',
            },
        ),
    ]
