# Generated by Django 6.0.4 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_citationurlcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorysnapshot',
            name='archival_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the repository was archived, if applicable (GitHub only)', null=True),
        ),
    ]
