# Generated by Django 6.0.6 on 2026-06-09 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_systemversion_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Company'), (2, 'University'), (3, 'Individual'), (4, 'Research Lab'), (5, 'Non-profit Corporation')], null=True, verbose_name='Organization Type'),
        ),
        migrations.AddConstraint(
            model_name='systemversion',
            constraint=models.UniqueConstraint(condition=models.Q(('approved', False)), fields=('system',), name='unique_pending_version_per_system'),
        ),
    ]
