# Generated by Django 6.0.6 on 2026-06-11 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_systemversion_unique_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='former_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Previous names this organization was known by'),
        ),
    ]
