# Generated by Django 6.0.6 on 2026-06-11 17:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_systemversion_former_names_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='wikipedia_url',
            field=models.ForeignKey(blank=True, help_text="URL of the organization's Wikipedia page", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_wikipedia_urls', to='core.citationurl'),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='former_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Previous names of the system'),
        ),
    ]
