# Generated by Django 6.0.6 on 2026-06-12 01:00

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_organization_wikipedia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationurl',
            name='last_statuscode',
            field=models.PositiveIntegerField(blank=True, db_comment='HTTP Status Code', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='The color of the logo', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='systemversion',
            name='logo_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='The color of the logo', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
