# Generated by Django 6.0.6 on 2026-06-15 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_logo_color_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Company'), (2, 'University'), (3, 'Individual'), (4, 'Research Lab'), (5, 'Non-profit'), (6, 'Government')], null=True, verbose_name='Organization Type'),
        ),
        migrations.CreateModel(
            name='SystemVersionCodingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(limit_choices_to={'attribute__slug': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='system_coding_agents', to='core.attributeoption')),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_agent_entries', to='core.citationurl')),
                ('system_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_agent_entries', to='core.systemversion')),
            ],
            options={
                'ordering': ('agent__name',),
                'unique_together': {('system_version', 'agent')},
            },
        ),
        migrations.AddField(
            model_name='systemversion',
            name='coding_agents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__slug': 'agent'}, related_name='+', through='core.SystemVersionCodingAgent', to='core.attributeoption', verbose_name='Coding Agents'),
        ),
    ]
