# Generated by Django 6.0.6 on 2026-06-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_systemversion_coding_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='linkedin_url',
        ),
    ]
