# Generated by Django 6.0.6 on 2026-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_remove_systemversion_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stock_delisted',
            field=models.BooleanField(blank=True, help_text='True if the stock is no longer publicly traded', null=True),
        ),
    ]
