# Generated by Django 6.0.6 on 2026-06-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_add_organization_stock_delisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpagemeta',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for search engines and social media previews (og:description).'),
        ),
    ]
