# Generated by Django 6.0.6 on 2026-07-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_add_organization_stock_delisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='crunchbase_url',
            field=models.ForeignKey(blank=True, help_text="URL of the organization's Crunchbase page", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_crunchbase_urls', to='core.citationurl'),
        ),
        migrations.AddField(
            model_name='systemversion',
            name='blog_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_blog_urls', to='core.citationurl', verbose_name='Engineering Blog URL'),
        ),
    ]
